# Generated by Django 5.2.7 on 2025-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='user', max_length=10),
        ),
    ]
