# Generated by Django 5.2.7 on 2025-11-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
