# Generated by Django 5.2.7 on 2025-11-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file_size',
            field=models.BigIntegerField(default=250, help_text='File size in bytes'),
            preserve_default=False,
        ),
    ]
